# Generated by Django 5.2.7 on 2025-11-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
